export const wedding = {
  bride: "Opeyimika",
  groom: "Chima",
  date: "2026-11-14T12:00:00+01:00",
  venue: "Shaded Garden",
  area: "Anthony, Lagos",
  quote: "Somewhere between hello and forever, we found our favourite person.",
  story: [
    "Well, it started with a video.",
    "A mutual friend posted a church content video on his status, and somewhere in that sea of faces, he saw her. Curious, he asked for her contact — but before it could be shared, he had already found her on Instagram.",
    "Eventually the contact was shared. Then came the call. They spoke, they laughed, they talked some more. What began as one simple conversation became many more conversations, then memories, then a friendship, then love.",
    "Looking back now, it's almost funny to think that something as ordinary as a church video could lead here. But perhaps it was never ordinary at all.",
    "We found each other. We chose each other. And now, we choose forever.",
  ],
  programme: [
    { time: "12:00 PM", title: "Holy Matrimony", note: "Doors open 11:30" },
    { time: "2:00 PM", title: "Cocktails & Photos", note: "" },
    { time: "3:30 PM", title: "Reception & Banquet", note: "" },
    { time: "7:00 PM", title: "After-party", note: "Dancing shoes required" },
  ],
  dressCode: "Come in your black tie for the gents and your church dress for the ladies. The reception is held in a garden, so please wear appropriate footwear.",
  registry: "https://giftchimaandope.com",
  hashtag: "#ChimaAndOpe",
  faqs: [
    { q: "How do I get to the venue?", a: 'The venue is accessible by bus and car. You can find the exact address by searching "Shaded Gardens" on any online map.' },
    { q: "What safety precautions are in place?", a: "We've limited the number of guests for your safety and comfort. If you're feeling unwell, please skip the ceremony — we totally understand and can celebrate another time." },
    { q: "What is the dress code?", a: "Come in your black tie for the gents and your church dress for the ladies, and make sure you're comfortable! The reception will be held in a garden, so please wear the appropriate footwear." },
    { q: "Can I bring a plus one?", a: "Plus ones are by invitation. Check your RSVP form." },
  ],
};